### ISSUE TITLE
itdb_test.py ERROR

### ISSUE THREAD

**Issue by JMdroid** [notro/fbtft_test#1]
Hello
itdb_test.py file to run I get the following error:

ERROR: could not insert 'fbtft': Exec format error
Traceback (most recent call last):
  File "itdb_test.py", line 11, in <module>
    ensure_fbtft()
  File "/home/pi/fbtft_test/fbtft.py", line 58, in ensure_fbtft
    sudocall(["modprobe", "fbtft"])
  File "/home/pi/fbtft_test/fbtft.py", line 16, in sudocall
    raise OSError
OSError

Why?

**Comment by notro** [comment]
Use `dmesg` to get more info about the error.

**Comment by JMdroid** [comment]
I executed again and sent you the last record that has given me the dmesg command

[    2.166370] mmc0: new high speed SDHC card at address 0007
[    2.182984] mmcblk0: mmc0:0007 SD8GB 7.42 GiB
[    2.194056]  mmcblk0: p1 p2
[    2.312375] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.320140] Indeed it is in host mode hprt0 = 00001101
[    2.522905] usb 1-1: New USB device found, idVendor=0424, idProduct=9512
[    2.530772] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.539890] hub 1-1:1.0: USB hub found
[    2.545065] hub 1-1:1.0: 3 ports detected
[    2.822410] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.900203] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.910115] VFS: Mounted root (ext4 filesystem) on device 179:2.
[    2.927308] devtmpfs: mounted
[    2.931340] Freeing init memory: 132K
[    2.943122] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.951161] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.963046] smsc95xx v1.0.4
[    3.027539] smsc95xx 1-1.1:1.0: eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:d4:1a:ee
[    3.132525] usb 1-1.3: new low-speed USB device number 4 using dwc_otg
[    3.253112] usb 1-1.3: New USB device found, idVendor=0e8f, idProduct=0020
[    3.261132] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.270432] usb 1-1.3: Product: PS2toUSB Adapter
[    3.276166] usb 1-1.3: Manufacturer: GASIA
[    3.292609] input: GASIA PS2toUSB Adapter as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input0
[    3.305818] hid-generic 0003:0E8F:0020.0001: input,hidraw0: USB HID v1.10 Keyboard [GASIA PS2toUSB Adapter] on usb-bcm2708_usb-1.3/input0
[    3.337355] input: GASIA PS2toUSB Adapter as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.1/input/input1
[    3.350095] hid-generic 0003:0E8F:0020.0002: input,hidraw1: USB HID v1.10 Mouse [GASIA PS2toUSB Adapter] on usb-bcm2708_usb-1.3/input1
[    4.415537] udevd[154]: starting version 175
[    5.326167] bcm2708_spi bcm2708_spi.0: master is unqueued, this is deprecated
[    5.470856] bcm2708_spi bcm2708_spi.0: SPI Controller at 0x20204000 (irq 80)
[    5.619907] Registered led device: led0
[   14.977944] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   15.439929] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   24.645693] smsc95xx 1-1.1:1.0: eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   30.176051] Adding 102396k swap on /var/swap.  Priority:-1 extents:2 across:510032k SS
[  215.601858] fb_sys_fops: disagrees about version of symbol module_layout
[  300.315666] fb_sys_fops: disagrees about version of symbol module_layout

**Comment by notro** [comment]
Have you built the kernel or modules your self?

There's a version mismatch between the kernel and the module fb_sys_fops which fbtft depends upon.

**Comment by JMdroid** [comment]
I have not built the kernel
kernel version I am using is the 3.6.1 +

  image I am using is the 2013-05-25-wheezy-raspbian-2013-07-07-fbtft.zip and have upgraded later with rpi-update repository.

**Comment by notro** [comment]
rpi-update can't be used. It overwrites the kernel/modules with one that doesn't have support for the FBTFT drivers.
I'm currently working on a solution where rpi-update can be used against a different repository which has FBTFT support.

**Comment by JMdroid** [comment]
I'll try with other previous images and see if it works

**Comment by JMdroid** [comment]
hello

probe to build an image and included the driver as you indicate in the Repositori fbtft
and it has worked perfectly both ITDB adapter as the SPI circuit but with the latter I can not put touchpanel works that are malformations of the screen image. Why?

**Comment by notro** [comment]
Which display do you have working?
And you have successfully tried both parallel and SPI interface modes?
- [url=http://www.raspberrypi.org/phpBB3/viewtopic.php?f=41&t=43702]Raspberry PI LCD Adapter Kit[/url]
- [url=https://github.com/notro/fbtft/wiki/SPI-interface-circuit]SPI interface circuit[/url]

Does the screen become garbled when you use the touchpanel and the SPI-interface?
Excatly what do you do that corrupts the displays?

**Comment by JMdroid** [comment]
I use the screen wil itdb02-2 .. 8 "itead study"
http://imall.iteadstudio.com/display/tft-lcm/im120419009.html

I work two parallel modes as both spi

to use the parallel mode "LCD PI Adapter Kit" "itead study"
http://imall.iteadstudio.com/im130425001.html

spi mode to use the circuit you propose in the repository fbtft
https://github.com/notro/fbtft/wiki/SPI-interface-circuit

but to put to work the touchpanel and the screen is when the image begins to distort

**Comment by notro** [comment]
> but to put to work the touchpanel and the screen is when the image begins to distort

I haven't experienced this myself nor had any reports about it.

Does this happen both with the SPI circuit and in parallel mode?

Does it happen without the touch driver (ads7846) loaded?

In SPI mode with the touch driver loaded, does `evtest` give any output when you touch the panel?

```
sudo apt-get install evtest
evtest
```

evtest will list the available input sources. With the touch driver loaded, ADS7846 will be in the list.

The touch panel won't work in parallel mode with that Adapter kit, because the touch controller isn't wired to match up with the Raspberry Pi SPI interface.

**Comment by JMdroid** [comment]
I have it connected to the SPI circuit and works well the visualization of the display and touchpanel but touchpanel touch the finger is when you start to distort the screen.

evtest is installed and the ADS7846 driver is loaded.

**Comment by notro** [comment]
I'm sorry but I don't know what may cause your problem.
Here is a similar problem on another display: http://www.raspberrypi.org/phpBB3/viewtopic.php?p=392342#p392342

**Comment by JMdroid** [comment]
thanks for your help

will try to locate the failure to give a solution and I will give to the problem commented
